### ISSUE TITLE
Support for names and slugs to be longer than 100 characters?

### ISSUE THREAD

**Issue by PaulMest** [jazzband/django-taggit#510]
Is there a way for names and slugs for tags to be larger than 100 characters?

I see a PR from a few years ago (#279) was closed without merging.

Happy to submit a new PR if others would like support for larger tags, too.

**Comment by oliver-zhou** [comment]
I'm not sure if this needs to be merged into the project since you could subclass TagBase, but at a minimum the existing max_length value DOES seem like something that should be in the docs, explicitly mentioned in the customization section, since the docs don't seem to mention any limitations or warnings regarding a non-standard max_length. It does seem to be a relatively important element of usability.

**Comment by rtpg** [comment]
+1 on "custom tag", having a global configuration has its own can of worms (to be honest I would not recommend anyone use the base `Tag` model, building off a custom tag base will save you a lot of headache long term)
