### ISSUE TITLE
MyObject.objects.all().values()

### ISSUE THREAD

**Issue by michealjroberts** [jazzband/django-taggit#668]
How do we get a list of tags to be returned when utilising `queryset.values()`? Is this even possible?

**Comment by rtpg** [comment]
In the Django documentation for [values](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#values)

```
>>> Blog.objects.values('name', 'entry__headline')
<QuerySet [{'name': 'My blog', 'entry__headline': 'An entry'},
     {'name': 'My blog', 'entry__headline': 'Another entry'}, ...]>
```
so you should be able to do something like `MyObject.objects.values('tags__name')`. _However_ if you do this then you will get one copy of each element per tag (since it's a join across a many-to-many).

Honestly depending on how you're working through your problem I'd instead opt for doing it manually at the point of consuming the result:

```
for obj in MyObject.objects.all().prefetch_related('tags').iterator():
    # do stuff
    tags = obj.tags.all()  # this will be prefetched
```

you should also profile the performance on stuff like `prefetch_related`. Less queries doesn't necessarily mean better performance, depending on query sizes and your workload.
