### ISSUE TITLE
TaggedItem entries no longer being created

### ISSUE THREAD

**Issue by mikey555** [jazzband/django-taggit#677]
I have a tag field called diet_tags that has worked properly up until recently. 

```
# diet_tag field and through model
class Meal(models.Model):
    ....
    diet_tags = TaggableManager(through=DietTaggedMeal, related_name='diet_tags', verbose_name='Diet tags', blank=True)

class DietTaggedMeal(TaggedItemBase):
    content_object = models.ForeignKey('Meal', on_delete=models.CASCADE)
```

After experimenting, I realized that TaggedItem entries weren't being created when I entered new or existing tags in the diet_tags field in admin.
When saving a Meal, the diet_tags field is saved properly, and an entry does result in the through model, DietTaggedMeals. However, I cannot figure out why entries aren't created in TaggedItem.

The one culprit I have is a migration I made around the time this issue appeared. I made a new model that mistakenly inherits `TaggedItemBase` instead of the regular `models.Model`. (It was originally to be a tag field but I decided on using it with a ForeignKey field instead.)

```
# CuisineCategory field and model
class CuisineCategory(TaggedItemBase):    # mistake! should've inherited models.Model
    name = models.CharField(max_length=100)
    seo_slug = models.CharField(max_length=100)
    created_at = models.DateTimeField(null=True, default=now)

    objects = CuisineCategoryQueryset.as_manager()

class Meal(models.Model):
    ....
    cuisine_category = models.ForeignKey(CuisineCategory, on_delete=models.SET_NULL, null=True, blank=True, related_name='cuisine')
```

I began creating CuisineCategory entries with no issues - apart from me having to create a tag each time I created a CuisineCategory entry (since TaggedItemBase requires a tag FK field). So I continued on without realizing things weren't working right with TaggedItem.

I'm not sure that the CuisineCategory migration is causing this issue. I've tried reverting the CuisineCategory migration by removing the cuisine_category field and deleting the CuisineCategory model, but the issue with diet_tags still remains. I've also tried changing CuisineCategory's subclass.

- diet_tag field saves properly
- entry properly created in through model DietTaggedMeal
- no entry is created in TaggedItem

Please let me know if I've left anything out that would be informative.

**Comment by rtpg** [comment]
I don't think `TaggedItemBase` would be a problem here, given that it's basically just adding a field and messing around with some helper functions....

Looking at your example I can't see what issue would be happening here except potentially that you are querying the wrong `TaggedItem` model. 

You're saying the `diet_tags` stuff saves properly right? So what happens if you get an instance of `Meal` in a django shell `python manage.py shell` and do something like `for tag_item in meal.diet_tags.all(): print(tag_item.tag)`? If you see something there it's clearly being saved in _some_ place. 

Writing this out... I think I realized the issue. You are setting a custom `through` table, so `DietTaggedMeal` _is_ your `TaggedItem` table for `Meal`s. `TaggedItem` is the default through table but you overwrote it so it's using a different table.

If you want to share the tags across models, you need to use a generic foreign key (which is how `TaggedItem` is implemented). But tyhe way you set things up means that you have a specific table _jusst_ for meal tags.

**Comment by rtpg** [comment]
Closing this out for now, but I'm 95% sure you aren't querying on the right table (especially if the data is showing up)
