### ISSUE TITLE
Using UUID, ForeignKey, and custom tag simultaneously raises IntegrityError

### ISSUE THREAD

**Issue by pierremonico** [jazzband/django-taggit#704]
I am trying to implement a Manager that:

- Uses a custom tag model
- Uses a `ForeignKey` instead of a `GenericForeignKey`
- Uses `UUID` as a primary key 

I followed the docs and came up with the following:
```
from django.db import models

from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase, TagBase


class MyCustomTag(TagBase):
    name = models.CharField(max_length=140)


class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    content_object = models.ForeignKey('docs.Document', on_delete=models.CASCADE)
    tag = models.ForeignKey(
        MyCustomTag,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )
```

My model is as follows:
```
from django.db import models
from taggit.managers import TaggableManager

from .tags import UUIDTaggedItem

class Document(models.Model):
    name = models.CharField(max_length=140)

    tags = TaggableManager(through=UUIDTaggedItem)
```

Trying to save the document in the admin raises and `IntegrityError`. More specifically `NOT NULL constraint failed: docs_uuidtaggeditem.content_object_id` and `UUIDTaggedItem matching query does not exist.`. 

I guess inheriting from `TaggedItemBase` allows to use a `ForeignKey` by setting `content_object`, but then excludes the possibility to add a custom `tag` attribute. **Is it either/or or is there a way to achieve what I am trying to do?** 

[I pushed a minimal repository where the error can be reproduced](https://github.com/pierremonico/taggit-example). Just run the migrations, go to the admin and try to save a document. Thanks.

**Comment by auvipy** [comment]
were you able to generate migrations with them?

**Comment by pierremonico** [comment]
> were you able to generate migrations with them?

Yes. You can reproduce the error [on the example repo I posted](https://github.com/pierremonico/taggit-example).

**Comment by rtpg** [comment]
@pierremonico sorry for the delay on this, I have looked through your example and I think you have kind of mixed up several concepts here, leading to your issues. The short version is "just use `TaggedItemBase`".

Firstly, I'm going to try and cover the UUID thing. UUID-based primary keys are a propery of _the model itself_, not of the tags. So for example if you want a UUID-based primary key on your model you end up doing

```python
import uuid
from django.db import models

class MyUUIDModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```
^ in particular the `primary_key=True` thing determines that you end up using a UUID as a primary key. Once you do that you gotta fidget with your `ForeignKey` to get those to work, gonna leave that as homework. The main thing tho is that the UUID stuff isn't really a property of the tagged items, but of the original model.

So what is `GenericUUIDTaggedItemBase` for? It's for **Generic** UUID stuff. Generic foreign keys are basically "some primary key + a content type", which means that tags can be used across model types (your tags can be used on documents _and_ clients, for example). But here you want a non-generic thing, so you can just use `TaggedItemBase`! Basically your error is because you weren't using a generic foreign key, but a standard one.

Aside: while you might want UUIDs on your document, I would recommend not using them as primary keys, and instead just defining a `uuid` field but letting the database use the default `pk` internally. For stuff like APIs etc, you can still use UUIDs for lookup, of course! But the default integer stuff is more performant (supposedly, might be less true nowadays) and you won't be swimming upstream. I use UUIDs as exposed identifiers and then override lookup functions to use that instead of the pk. 

Anyways yeah if you use `TaggedItemBase` your problems in your sample go away (tested with your sample app, thank you for going through that! Very helpful). And you won't be using a GFK, and you'll have your custom tag. Making UUIDs be your primary key is a bit of a separate thing you might need to do (and if this is a running system it might be hard to migrate to).
