### ISSUE TITLE
I wonder what one can do if one wants to "$" or "&" as tags?

### ISSUE THREAD

**Issue by xxl4tomxu98** [jazzband/django-taggit#731]
When I do this, I got url reverse error, unidecode does not seem to fix it.  error message:

NoReverseMatch at /learning/
Reverse for 'filter-tag' with arguments '('',)' not found. 1 pattern(s) tried: ['learning/filter_by_tag/(?P<tag>[-a-zA-Z0-9_]+)/$']

**Comment by rtpg** [comment]
When you create a tag with that in the name, what do you end up having as a value for `slug` for those tags (you could probably see it in the admin)? Right now it seems that `TagBase.slugify` should transform the name into something that's usable in a URL, _but_ it seems like if you don't have `unidecodify` installed then you no-op (see [here](https://github.com/jazzband/django-taggit/blob/4f89a016d7ac746a8e05772d63ef47e9464eb8da/taggit/models.py#L8))

**Comment by xxl4tomxu98** [comment]
what you are saying is that TagBase.slugify would transform the name into empty string " ". The problem is that when this happens, not only it is not usable, it will give an error as "NoReverseMatch exception".

**Comment by rtpg** [comment]
right, there's a line that gets drawn somewhere on the slugification process.

The "good" news (especially if you haven't deployed your app yet) is you can work around this nicely by implementing your own `Tag` subclass instead of using the one out of the box. When you do that you can override the `slugify` method to do whatever makes sense for your use case.

You can also just write things up to look up by name instead of slug, on this view.

[here's some docs on using custom tags](https://django-taggit.readthedocs.io/en/latest/custom_tagging.html#TagBase). It's not a guaranteed hit of course.

I think this might be a bit of a "documentation request", bit of a "feature request". "Documentation" in that we should make it clearer to people when they use this that the default model is limiting, "feature" for "support more stuff in slugs/etc". 

Thinking about this more, we could just do an escape sequence thing in the slugs...

**Comment by xxl4tomxu98** [comment]
I agree, custom tags seem the way to go here. But the default tags in Taggit is shaky and error prone. The default methods "taggit.utils._parse_tags" and "django.utils.text.slugify" all needs to be examined and consider all the edge cases.
