### ISSUE TITLE
Getting error while fetching tag field in pre-save signals 

### ISSUE THREAD

**Issue by naveedur** [jazzband/django-taggit#817]
I am using django-taggit but unable to get tags when I print(instance.tags) in pre-save signal method. And getting this error.
```
resource objects need to have a primary key value before you can access their tags
```

models.py
```
class resource(models.Model):

    title=models.CharField(max_length=100)
    size=models.CharField( max_length=20, default="")
    desc=models.TextField(default="")
    file=models.FileField(default="", blank=True)
    url= models.URLField(max_length=200, blank=True)
    varient=models.CharField(max_length=100, default="")
    Brand = models.ForeignKey(brand,on_delete=models.CASCADE, default="")
    Model = models.ForeignKey(model,on_delete=models.CASCADE, default="")
    Categories = models.ForeignKey(category,on_delete=models.CASCADE, default="")
    update_at=models.DateField(auto_now=True)
    slug=models.SlugField(default="", unique=True, blank=True)
    Tags = TaggableManager(blank=True)`
```

pre-save function
```
def tag_set(sender, instance, **kwargs):

   print(instance.Tags) 

pre_save.connect(tag_set, sender=resource)
```

**Comment by rtpg** [comment]
@naveedur tags are stored as a many-to-many relation, so `instance.Tags` actually fetches the data from the database. In order to save tags in the database, you want to first save the resource (why? because the tags are saved in a table that have an ID for the "tag object" that hold the name, and an ID for the resource itself)

Since you're in the pre-save method, your object is not saved... and nothing is in the database! 

So kinda dependent on what you are doing, but you can't really access the tags in the pre-save method in a way that you would like. The tags are _not_ stored on the resource itself, but in a separate table. I understand that this is a bit conceptually confusing though.

**Comment by naveedur** [comment]
> @naveedur tags are stored as a many-to-many relation, so `instance.Tags` actually fetches the data from the database. In order to save tags in the database, you want to first save the resource (why? because the tags are saved in a table that have an ID for the "tag object" that hold the name, and an ID for the resource itself)
> 
> Since you're in the pre-save method, your object is not saved... and nothing is in the database!
> 
> So kinda dependent on what you are doing, but you can't really access the tags in the pre-save method in a way that you would like. The tags are _not_ stored on the resource itself, but in a separate table. I understand that this is a bit conceptually confusing though.

**Comment by naveedur** [comment]
@rtpg, thanks for the reply. I understand what you are saying. But is there any method to do this.
