### ISSUE TITLE
django-taggit get number of posts that use a particular tag

### ISSUE THREAD

**Issue by iamaryanshandilya** [jazzband/django-taggit#824]
What I want to do is to get the number of posts for a particular tag, kind of like how Instagram and Twitter do, I found some solutions  [this](https://github.com/jazzband/django-taggit/issues/203) and [this](https://stackoverflow.com/questions/68627137/django-taggit-aggregation-query-to-return-count-per-tag). I want to clarify if this is the only way to achieve what I want. Wouldn't it be bad to calculate the number of posts every time someone tries to access a tag?

So, I created a custom tag by following these [instructions](https://django-taggit.readthedocs.io/en/latest/custom_tagging.html), and have added a num_posts field.
```
class Hashtag(TagBase):
    num_posts = models.IntegerField(default=0, blank=False, null=False)
    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")`
```

So, how do I increase the num_posts value whenever a new post uses this tag? Or when a post creates a new tag, automatically assign the value of 1 to num_posts. I tried to look into the source code of django-taggit, specifically the TaggableManager, to see if I can override something there and get the intended results. So far I was not able to do anything. Can someone please give me some assistance?

**Comment by iamaryanshandilya** [comment]
I did find something [here](https://django-taggit.readthedocs.io/en/latest/custom_tagging.html#custom-tag), though I have some doubts, like suppose I try to add 3 different tags to a model and wish to have different values for my extra parameters(each parameter with a different value). How am I supposed to do that? 

`my_food.tags.add("tag_name1", "tag_name2", tag_kwargs={"my_field":3})` 

The line above seems to add the same value. Also, when I remove a tag, how do I then pass the value of tag_kwargs, because it throws an error right now. 

`TypeError: _TaggableManager.remove() got an unexpected keyword argument 'tag_kwargs'`

**Comment by iamaryanshandilya** [comment]
It works for add() function but I am having trouble adding the tag_kwargs in set(). I checked in the source code and found that any kwargs other than clear are assigned the value of None by default. Is there a workaround other than calling add() every time I wish to add a new tag in my model

**Comment by rtpg** [comment]
@iamaryanshandilya welcome to eternal problems of caching! Now if I were you I would probably not try to store the number ont he tag base, and instead write a function like:

```
def get_num_posts(tag_name):
     # or whatever calculation
     cached_result = cache.get(tag_name)
     if cached_result is not None:
          return cached_result
    # save the result for an hour, invalidation will let to recalculations
    cache.set(tag_name, Hashtag.objects.filter(name=tag_name).count(), timeout=3600) 
    return cache.get(tag_name)
```

Using Django's [cache API](https://docs.djangoproject.com/en/4.1/topics/cache/#the-low-level-cache-api) to store the value 

If you try to recalc on every save you'll potentially be triggering a big calculation way more often than needed, unless you really need the _exactly right number of tags_. Depends on the problem space though. 

If you have only a couple hundred items per tag, just calculating on page load might be fine! If you have many tens of thousands of rows, though, then calculating on page load is bad, but calculating on save _is also bad_, because it will mean saves will be very costly, for a number that will maybe invalidate itself quite soon. This caching I wrote up should be more flexible for most cases, if you're alright with an inaccurate number.
